# -*- coding: utf-8 -*-
"""natchuu nm projectipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZFva4fBY6RRyr_LsMoT1dFtQk-1Oz9w
"""

!pip install gradio pandas

import pandas as pd

# Load the dataset
faq_df = pd.read_csv("faq_data.csv")

# Display first few rows
faq_df.head()

# Shape of the dataset
print("Shape:", faq_df.shape)

# Column names
print("Columns:", faq_df.columns.tolist())

# Check for missing values
print("Missing values:\n", faq_df.isnull().sum())

# Check for duplicates
print("Duplicate rows:", faq_df.duplicated().sum())

def chatbot_response(user_input):
    user_input = user_input.lower()
    for _, row in faq_df.iterrows():
        if row['question_keywords'] in user_input:
            return row['response']
    return "Sorry, I couldn't understand that. Please type 'help'."

import gradio as gr

# Gradio chatbot interface
gr.Interface(
    fn=chatbot_response,
    inputs=gr.Textbox(lines=2, placeholder="Type your customer support question..."),
    outputs="text",
    title="🤖 Intelligent Customer Support Bot",
    description="Ask questions like 'refund', 'order status', 'payment issue', etc."
).launch(share=True)